### ISSUE TITLE
Move the processing logic from OpenHuntingData into it's own repo, add here as a submodule

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/PublicLands#3]

**Comment by JesseCrocker** [comment]
@nathancahill Does this seem right?

**Comment by nathancahill** [comment]
:+1:

**Comment by nathancahill** [comment]
Probably generalize the submission form too right?

**Comment by JesseCrocker** [comment]
Yeah, can we make the submission form just read schema/source.json and create the properties field from that?

**Comment by JesseCrocker** [comment]
https://github.com/OpenBounds/Processing
