### ISSUE TITLE
USFS lands missing holes

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/PublicLands#66]
Old gaia public lands layer, was correct
![oldcorrectoverlay](https://cloud.githubusercontent.com/assets/2048291/19875943/c6495e3c-9f96-11e6-90e6-ff2c741a8744.jpg)

New layer, incorrect
![newincorrectoverlay](https://cloud.githubusercontent.com/assets/2048291/19875948/d4e3fc04-9f96-11e6-964f-88a1bcc61be3.jpg)

**Comment by kdough03** [comment]
Tried various files at http://data.fs.usda.gov/geodata/edw/datasets.php, but none of them exclude the private lands. Will contact USFS directly.

**Comment by JesseCrocker** [comment]
Fixed
